name: Check Function Length

on: pull_request

jobs:
  check-function-length:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pylint
        run: pip install pylint

      - name: Create pylint config
        run: |
          echo "[DESIGN]" > .pylintrc
          echo "max-locals=10" >> .pylintrc
          echo "max-args=5" >> .pylintrc
          echo "max-statements=15" >> .pylintrc
          echo "[MESSAGES CONTROL]" >> .pylintrc
          echo "disable=all" >> .pylintrc
          echo "enable=design" >> .pylintrc

      - name: Run pylint
        run: pylint --rcfile=.pylintrc src/
